### PR TITLE
Enhance documentation

### LINKED ISSUE #121: Add documentation for new-major features
We should add documentation for the following topics:
1. Working of Safety-controller
2. Working of Machine-deployment with regards to priorities of Machine.
    - the feature we implemented for autoscaler integration.
3. Notable features in README at root location.
   - Rolling update, rollback, pause, autoscaler integration, health-check.
4. Working of base controllers
   - Behavior of machine/set/deployment controllers in different scenarios.
   - Maybe the way autoscaler Q&A looks like: 
     https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md
5. Working of bootstrap-token mechanism with Gardener at the time of machine-creation. 
   - This may fit-in gardener repository rather.

This should help larger audience to understand the internals/working of mcm, also help us re-directing many of the queries here.

### PR DESCRIPTION
**Pull request by hardikdr**
**What this PR does / why we need it**:
Let's please enhance the documentation together by adding more frequently asked questions and answers. 

**Which issue(s) this PR fixes**:
Fixes #121 

**Special notes for your reviewer**:
PR is maintained on a branch under gardener org itself, please feel free to add/update questions/answers in FAQ.md. Once we see a good-enough content - we shall merge it.

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by PadmaB** [comment]
@hardikdr thanks for this PR. Can you also update the 'Future Plans' section [here](https://github.com/gardener/machine-controller-manager/blob/master/docs/design/README.md). It is out-dated

**Comment by hardikdr** [comment]
Yes sure, I shall update the section, thanks.

**Comment by hardikdr** [comment]
Any chance we can get this PR going somehow? @prashanth26 @ggaurav10 @ashwani2k 

Idea is, everyone contributes here the questions and answers, and we prepare a basic FAQ, the way we have for [autoscaler](https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/FAQ.md) .

**Comment by hardikdr** [comment]
Closing this due to inactivity for a long time.

**Pull request closed without merging**
