### PR TITLE
Azure: use VM image purchase plan if required

### PR DESCRIPTION
**Pull request by MSSedusch**
**What this PR does / why we need it**:
Some Azure images, for example Garden Linux, force to provide a plan during VM deployment. This PR analyzes the image and if the image has a purchase plan provide that plan during deployment time.

**Which issue(s) this PR fixes**:
Fixes # Error when creating a VM from an image that requires a purchase plan

**Special notes for your reviewer**:

**Release note**:

```improvement user
Azure: Add support for custom image plans for VMs
```

### CODE REVIEW

**Comment by prashanth26** [comment]
I think there is an issue with linting/dependecy mgmt. This is the error reported by the linter.

```
build github.com/Azure/azure-sdk-for-go/services/marketplaceordering/mgmt/2015-06-01/marketplaceordering: cannot load github.com/Azure/azure-sdk-for-go/services/marketplaceordering/mgmt/2015-06-01/marketplaceordering: open /tmp/build/d56d9853/pull-request-gardener_machine-controller-manager-pr_master/vendor/github.com/Azure/azure-sdk-for-go/services/marketplaceordering/mgmt/2015-06-01/marketplaceordering: no such file or directory
```

**Comment by prashanth26** [comment]
I checked the PR with simple tests to create & delete coreOS and GardenerLinux images. It seems to be working well. However, the GardenerLinux node couldn't join as probably the userData was not as expected, which is fine. 

Just added a few comments/logs here - https://github.com/MSSedusch/machine-controller-manager/pull/1.

**Comment by prashanth26** [comment]
@gardener/mcm-maintainers - PTAL.

**Comment by vpnachev** [comment]
I've just tested this PR e2e and it has successfully created VM that later joined as k8s node.
Thank you very much @MSSedusch !

/lgtm
/kind/enhancement|
/priority/critical
/platform/azure

**Comment by gardener-botmanager** [comment]
@vpnachev Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by gardener-botmanager** [comment]
@vpnachev Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by gardener-botmanager** [comment]
@vpnachev Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by gardener-botmanager** [comment]
@vpnachev Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by gardener-botmanager** [comment]
@vpnachev Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by gardener-botmanager** [comment]
@vpnachev Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by gardener-botmanager** [comment]
@vpnachev Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by gardener-botmanager** [comment]
@vpnachev Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by prashanth26** [comment]
@MSSedusch can you please merge this into this branch? Just some logs - https://github.com/MSSedusch/machine-controller-manager/pull/1/files

**Comment by prashanth26** [comment]
@vpnachev - Thanks for testing it. Appreciate the help. We will try to  merge and create a release by EOD.

**Comment by MSSedusch** [comment]
@prashanth26 merged your PR
thanks

**Pull request merged**
