### PR TITLE
Update `github.com/Masterminds/semver` to v3

### PR DESCRIPTION
**Pull request by maboehm**
**What this PR does / why we need it**:
Updates the package, which has been on v3 for a while. The API and behaviour in our cases are the same.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @maboehm for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by maboehm** [comment]
Is this project still being actively maintained? 🙈

**Comment by elankath** [comment]
We will check whether this has any impact  before merging.

**Comment by unmarshall** [comment]
>Is this project still being actively maintained?

Yes, this project is actively maintained. The contributions are steady and are going to increase quite a bit in the near future.  So you can rest assured. There was a delay in responding to this PR because the contributors were busy with other requests.

**Review by rishabh-11 — APPROVED** [review]
/lgtm

**Pull request merged**
