### PR TITLE
Minor nits

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
Switch deprecated funcs:
- `session.New → session.NewSession`
- `client.Core - > client.CoreV1`
- `./hack/generate-code` with the new year

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Comment by hardikdr** [comment]
One of the unit tests seems to be failing, can you please take a look? @ialidzhikov

**Comment by ialidzhikov** [comment]
> One of the unit tests seems to be failing, can you please take a look? @ialidzhikov

I think it is failing randomly. I managed to reproduce it locally once and then the same tests passed several times. 😕

**Comment by ialidzhikov** [comment]
Fixed the unit test flake. But the integration tests are failing.
Is there a known issue with them?

**Comment by hardikdr** [comment]
Thanks @ialidzhikov .
Integration tests also seem to be flaking, we are looking into it.

**Pull request merged**
