### PR TITLE
Keep the last failed operations in the machinedpeloyment and machineset

### PR DESCRIPTION
**Pull request by ggaurav10**

### CODE REVIEW

**Comment by prashanth26** [comment]
We probably need to discuss how these statuses and healthy machines info would be passed on the gardener?

**Comment by hardikdr** [comment]
Agreed with Prashanth, we need to discuss around how Gardener can independently consume this change.

**Comment by ggaurav10** [comment]
Based on discussions today, closing this PR as current implementation (#89) of updating failed machines' status into machinedeployment and machineset is as per the needs of Gardener.

**Comment by prashanth26** [comment]
Looks good.

**Pull request closed without merging**
