### PR TITLE
Handle `PodDisruptionBudget` `policy/v1`

### PR DESCRIPTION
**Pull request by shafeeqes**
**What this PR does / why we need it**:
The policy/v1beta1 API version of PodDisruptionBudget will no longer be served in v1.25.
We should migrate manifests and API clients to use the policy/v1 API version, available since v1.21

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6567

**Special notes for your reviewer**:

**Release note**:

```other operator
Migrated clients to use `policy/v1` `PodDisruptionBudget` for kubernetes versions >= 1.21. `policy/v1beta1` PDB is also supported but for k8s < 1.21
```

### CODE REVIEW

**Review by himanshu-kun — APPROVED** [review]
/lgtm
Thnx for the changes @shafeeqes

**Comment by shafeeqes** [comment]
Thanks for the review, Can we have a release with this PR included?

**Comment by himanshu-kun** [comment]
I am planning a release by EoD

**Pull request merged**
