### PR TITLE
Secrets moved to controlCoreObjects in tests

### PR DESCRIPTION
**Pull request by himanshu-kun**
**What this PR does / why we need it**:
- test framework for package `controller`  modified
- secrets now part of controlCoreObjects
- controlCoreClient used for fetching secrets

**Which issue(s) this PR fixes**:
Fixes # 616

**Special notes for your reviewer**:

**Release note**:

```bugfix developer
Fetches secrets from the correct (control) APIServer while running tests. 
```

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @himanshu-kun for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by AxiomSamarth — APPROVED** [review]

**Comment by AxiomSamarth** [comment]
reviewed/ok-to-test

**Review by prashanth26 — APPROVED** [review]
This looks great.

Thanks for this change.
/lgtm

**Comment by prashanth26** [comment]
/titile Test framework now fetches secrets from the correct (control) APIServer while running tests

**Pull request merged**
