### PR TITLE
Fix packet issues

### PR DESCRIPTION
**Pull request by deitch**
**What this PR does / why we need it**:

Fixes several issues with the Packet MCM:

* Tags were assumed to be a key-value map on input and then converted to an array of string. This was inconsistent with what Gardener passed to it, and added complexity. These are now a simple string array.
* SSH Keys were assumed to be a key-value map containing the key UUID and the fingerprint, but Packet doesn't consume anything other than the UUID. This also was inconsistent with what Gardener passed to it and added complexity. These are now a simple string array of the UUIDs.
* The SSH Keys were not being passed to Packet API in the driver. Now it is.

**Special notes for your reviewer**:
As discussed with @rfranzke on Slack.

**Do not merge this yet,** until I indicate that it is ready and remove the `[WIP]`. In addition to the above issues, there is a bug wherein it crashes. Once that is fixed, this will be ready to go.

EDITED: good to merge.

**Release note**:

```improvement operator
Fixes packet driver
```

### CODE REVIEW

**Comment by deitch** [comment]
Crashing bug is fixed, servers get created, it is a lovely thing!

Ready for you @rfranzke

**Comment by rfranzke** [comment]
Can you please fix the failing tests?

```
Summarizing 1 Failure:

[Fail] machine_util #syncMachineNodeTemplates ##table [It] Multiple taints with same key and value added to taint 
/tmp/build/a94a8fe5/pull-request-gardener_machine-controller-manager-pr_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/machine_util_test.go:85

Ran 133 of 133 Specs in 19.100 seconds
FAIL! -- 132 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestMachineControllerManagerSuite (19.10s)
```

@hardikdr @prashanth26 @ggaurav10 can you please check this PR and merge it if it looks good/you don't have any other suggestions? I guess @deitch already verified the functionality in his Packet environment.

**Comment by deitch** [comment]
> already verified the functionality in his Packet environment

I did, indeed. 

> Can you please fix the failing tests?

If there are changes needed to the PR to fix them, I am happy to do so, but I don't know what the issue is. Is it something relating to the changes I made? concourse doesn't give me access, so I am not sure what the multiple taints are.

**Comment by deitch** [comment]
Thanks @hardikdr !

**Comment by deitch** [comment]
Will this automatically pushed out a new image? I need to reference it in `gardener/gardener-extensions`.

**Pull request merged**
