### PR TITLE
Update github.com/Azure/azure-sdk-for-go

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
Recently we faced issues vendoring machine-controller-manager in other projects - for example gardener/gardener-extensions#463. gardener/gardener-extensions refers `github.com/Azure/azure-sdk-for-go@v32.6.0` while machine-controller-manager - `v26.1.0`. This PR updates also machine-controller-manager to use `v32.6.0`.
Also `github.com/Azure/go-autorest` is split into go submodules and this PR switches to the new submodule dependencies - ref https://github.com/Azure/go-autorest/#using-with-go-modules.

**Which issue(s) this PR fixes**:
Ref gardener/gardener-extensions#463

**Special notes for your reviewer**:

**Release note**:

```improvement operator
`github.com/Azure/azure-sdk-for-go` is updated to `v32.6.0`.
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
@gardener/mcm-maintainers , any feedback?

**Comment by hardikdr** [comment]
Thanks @ialidzhikov for the PR. We were checking if the upgrade of the vendor for Azure is breaking any of the functions semantically. 

As our integration test-pipeline is not enabled for Azure[explicitly disabled due to issues in past], I am wondering if you have tested your changes, if it works well? 
- At least for a happy path of creation/deletion/roll-outs of machines.

**Comment by ialidzhikov** [comment]
Yes, I made a docker image and using `imageVectorOverwrite` in provider-azure I tested scale up, scale down, creation and hibernation.
Double verification is always welcome.

**Comment by hardikdr** [comment]
I believe that should be sufficient then, thanks a lot. :) 
Merging.

**Pull request merged**
