### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by AxiomSamarth**
**What this PR does / why we need it**:
Improves documentation of MCM for reference on repository as well as via Gardener website.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```doc user
NONE
```

### CODE REVIEW

**Review by himanshu-kun — APPROVED** [review]
/lgtm

**Comment by himanshu-kun** [comment]
Would these be generated when I run `make generate`?

**Comment by AxiomSamarth** [comment]
>Also shall I merge this now ?

No no! /hold

>Would these be generated when I run make generate?

There is no `generate` rule in MCM's Makefile. I still have to add it. [This](https://github.com/gardener/machine-controller-manager/blob/0f8aa311bdc08903dad56fe25df3d3e3a309e39e/hack/api-reference/generate-spec-doc.sh_ file with the command should be run.

**Comment by AxiomSamarth** [comment]
/unhold 

@himanshu-kun Now, it is ready to be merged! Take a look and squash merge it.

**Review by himanshu-kun — APPROVED** [review]
/lgtm

**Pull request merged**
