### PR TITLE
Adding alternative approaches to proposal for GRPC based implementati…

### PR DESCRIPTION
**Pull request by ggaurav10**
…on of Cloud Providers for MCM
Adding alternative approaches to proposal for GRPC based implementation of Cloud Providers for MCM

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by hardikdr** [comment]
Should we merge this PR with caution on top mentioning the correct implementation/documentation?

**Comment by prashanth26** [comment]
Any update on what to do with this PR?

**Comment by hardikdr** [comment]
I guess we close this one for now.
We can later add a warning/note on top of this proposal, pointing to the latest implementation.

**Comment by ggaurav10** [comment]
Closing this PR as it is outdated now

**Pull request closed without merging**
