### PR TITLE
Updated k8s.io dependency to 0.18 

### LINKED ISSUE #402: Update vendoring to k8s 1.20/1.21
Logs of MCM:
```
I0201 07:37:20.264399       1 machine_safety.go:69] reconcileClusterMachineSafetyOvershooting: Start
I0201 07:37:20.264533       1 machine_safety.go:374] checkAndFreezeORUnfreezeMachineSets: MS:"shoot--garden--az-us2-cpu-worker-z1-6979c847b6" LowerThreshold:4 FullyLabeledReplicas:4 HigherThreshold:5
I0201 07:37:20.565096       1 machine_safety.go:95] reconcileClusterMachineSafetyOvershooting: End, reSync-Period: 1m0s
E0201 07:37:24.347148       1 machine.go:158] Could not fetch machine object machines.machine.sapcloud.io "shoot--garden--az-us2-cpu-worker-z1-6979c847b6-wbmqr" not found
E0201 07:37:24.349910       1 machine.go:158] Could not fetch machine object machines.machine.sapcloud.io "shoot--garden--az-us2-cpu-worker-z1-6979c847b6-4cpkc" not found
E0201 07:37:24.349993       1 machine.go:158] Could not fetch machine object machines.machine.sapcloud.io "shoot--garden--az-us2-cpu-worker-z1-6979c847b6-r6wnm" not found
E0201 07:37:24.350033       1 machine.go:158] Could not fetch machine object machines.machine.sapcloud.io "shoot--garden--az-us2-cpu-worker-z1-6979c847b6-5n7d8" not found
E0201 07:37:34.589908       1 machine.go:158] Could not fetch machine object machines.machine.sapcloud.io "shoot--garden--az-us2-cpu-worker-z1-6979c847b6-wbmqr" not found
E0201 07:37:34.592394       1 machine.go:158] Could not fetch machine object machines.machine.sapcloud.io "shoot--garden--az-us2-cpu-worker-z1-6979c847b6-r6wnm" not found
E0201 07:37:34.592409       1 machine.go:158] Could not fetch machine object machines.machine.sapcloud.io "shoot--garden--az-us2-cpu-worker-z1-6979c847b6-5n7d8" not found
E0201 07:37:34.592444       1 machine.go:158] Could not fetch machine object machines.machine.sapcloud.io "shoot--garden--az-us2-cpu-worker-z1-6979c847b6-4cpkc" not found
I0201 07:37:35.077956       1 machine_safety.go:105] reconcileClusterMachineSafetyAPIServer: Start
I0201 07:37:35.084685       1 machine_safety.go:174] reconcileClusterMachineSafetyAPIServer: Stop
E0201 07:37:55.073089       1 machine.go:158] Could not fetch machine object machines.machine.sapcloud.io "shoot--garden--az-us2-cpu-worker-z1-6979c847b6-wbmqr" not found
E0201 07:37:55.075920       1 machine.go:158] Could not fetch machine object machines.machine.sapcloud.io "shoot--garden--az-us2-cpu-worker-z1-6979c847b6-5n7d8" not found
E0201 07:37:55.075931       1 machine.go:158] Could not fetch machine object machines.machine.sapcloud.io "shoot--garden--az-us2-cpu-worker-z1-6979c847b6-4cpkc" not found
E0201 07:37:55.077233       1 machine.go:158] Could not fetch machine object machines.machine.sapcloud.io "shoot--garden--az-us2-cpu-worker-z1-6979c847
```

MCM doesn't reconcile machines anymore. Restarting MCM results in all the machines getting recreated again, after which the issue is resolved.

### PR DESCRIPTION
**Pull request by hardikdr**
**What this PR does / why we need it**: Upgrading the k8s.io dependencies to 0.18. 

This is needed mainly for the following reasons, on top of the usual need of upgrading the k8s.io dependencies:
- The cluster-autoscaler now uses the latest k8s-io dependency, and in order for MCM to be vendored in it, MCM also needs to vendor the compatible k8s.io packages. 
- Gardener/gardener also vendors v0.18.0 k8s.io packages, and in order to utilize its integration-test framework, we need to vendor g/g partially. This would also need MCM to vendor these k8s-io packages, to avoid package incompatibilities.

**Which issue(s) this PR fixes**:
Fixes #402 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Updated k8s.io dependency to 0.18.
```

### CODE REVIEW

**Comment by hardikdr** [comment]
Need to adapt the tests as well, open for review otherwise.
/hold

**Comment by hardikdr** [comment]
It seems with the latest vendor upgrade, MCM's fake-client is broken. I have adapted the test files according to the new client-signatures, but I see a plethora of the following errors for all the object-types while running unit tests and many of them are flaky, randomly pass/fail.

```
W1021 10:25:00.207800   17908 reflector.go:405] github.com/gardener/machine-controller-manager/pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.AWSMachineClass ended with: very short watch: github.com/gardener/machine-controller-manager/pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W1021 10:25:00.207859   17908 reflector.go:405] k8s.io/client-go/informers/factory.go:135: watch of *v1.PersistentVolume ended with: very short watch: k8s.io/client-go/informers/factory.go:135: Unexpected watch close - watch lasted less than a second and no items received
```
 
Easily reproducible by only fetching this branch and executing `ginkgo --cover pkg/controller/.`.

Essentially, the watches are being closed too frequently, and possibly there could be a race in opening and closing the watch. My gist is, the way we handle `FakeWatcher`, needs to be improved but fully sure.
- I so far, tried using `RaceFreeFakeWatcher`, disabling the trackers.Stop() to test, and a couple of other stuff but no success.

@prashanth26 @amshuman-kr I'd really appreciate it if you could also take a look if possible or have any suggestions around what could possibly be going wrong.

**Comment by prashanth26** [comment]
Hi,

I spent some time as well, but no conclusive results here. 

Yes, I do see a problem with the watch warnings. But I am starting the think about the reason for this. As with the changes here - https://github.com/prashanth26/machine-controller-manager/commit/eb7431c52648db925284b4a6f639b64471a26c01#diff-74318b2bd42ec70385a0c33d9f25798407345e911586f38642a6c7d627587cf2R1885-R1895. I see even a simple GET on the machine isn't returning the machine object as expected. Wondering if something new has changed with the k8s clients expecting more metadata than what we had before leading to failures in APIServer GET calls as well as watch closes. Also please have look at the comments - with late/deletion of `tracker.stop()` in the above single test the watch warnings go away, wondering if that helps us to infer the cause in any way.

Also, I see that most tests expect a few of them (2 sets of table tests) are working fine which doesn't explain why the GET above fails as many other tests with GETs are passing now. @hardikdr you can also take a look at my commit above and see if you observe the same.

**Comment by hardikdr** [comment]
thanks @prashanth26 .
Check the latest changes in the `machine_test.go`, fake clients now handle the empty namespaces differently.

I also made some more changes in the fakeclient, and the watch issue is gone, but there are still a couple of other issues due to the new vendors, need more time to investigate.

**Pull request closed without merging**
