### PR TITLE
Update docker images to use latest gcr copy

### PR DESCRIPTION
**Pull request by prashanth26**
**What this PR does / why we need it**:
This PR uses the latest gcr copy for docker images. Fixes any rate-limiting issues while building images. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by prashanth26** [comment]
/hold 
until test for https://github.com/gardener/machine-controller-manager/pull/572/files succeeds.

**Comment by prashanth26** [comment]
/unhold 
worked as expected.

**Review by hardikdr — APPROVED** [review]
/lgtm , thanks for the PR.

**Pull request merged**
