### PR TITLE
Specify more readable k8s dependencies

### PR DESCRIPTION
**Pull request by majst01**
Update k8s dependencies from 1.16.0 -> 1.16.15 and specify them by the tagged references instead the git-sha notation.
klog was also updated from v0.4.0 -> v1.0.0

This should make k8s dependency updates in the future more easy.

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @majst01 for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by hardikdr** [comment]
Looks good, I'll wait for the review from @prashanth26.

**Comment by majst01** [comment]
@prashanth26 if you show me the logs of the failed ci job i can try to fix it.

**Comment by prashanth26** [comment]
I see the unit tests (`make test-unit`) failing with several errors along the lines of

```
W0908 17:43:27.465694   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.OpenStackMachineClass ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.465712   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.PersistentVolumeClaim ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.465694   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.Node ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
•W0908 17:43:27.568217   25211 controller_utils.go:950] Node node-dummy not found while updating annotation. Err: nodes "node-dummy" not found
W0908 17:43:27.568275   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.AWSMachineClass ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.568302   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.PersistentVolumeClaim ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.568314   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.PersistentVolume ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.568325   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.Node ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
•W0908 17:43:27.671080   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.Node ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.671083   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.Secret ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.671088   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.PersistentVolumeClaim ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
E0908 17:43:27.773379   25211 machine_safety.go:192] SafetyController: Unable to GET on node objects APIServer is Not Reachable
•W0908 17:43:27.773442   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.MachineDeployment ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.773723   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.PersistentVolume ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.773771   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.AzureMachineClass ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.773749   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.MachineSet ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.773803   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.PersistentVolumeClaim ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
•W0908 17:43:27.877112   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.MachineDeployment ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.877129   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.GCPMachineClass ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.877150   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.MachineSet ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.877161   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.Machine ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.877160   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.PersistentVolume ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.877172   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.Node ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
•W0908 17:43:27.981910   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.OpenStackMachineClass ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.981942   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.GCPMachineClass ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.981965   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.Node ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.981971   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.PersistentVolume ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.981976   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.PersistentVolumeClaim ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.981979   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.Secret ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.981988   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.Machine ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:27.981990   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.MachineSet ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
E0908 17:43:28.084416   25211 machine_util.go:303] Error: Could not get the node-object or node-object is missing - err: "node \"test-node-0\" not found"
•W0908 17:43:28.084486   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.MachineDeployment ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:28.084523   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.Machine ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
E0908 17:43:28.187792   25211 machine_safety.go:184] SafetyController: Unable to GET on machine objects APIServer is Not Reachable
•W0908 17:43:28.187875   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.AzureMachineClass ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:28.187888   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.MachineSet ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:28.187904   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.GCPMachineClass ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:28.187921   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.AWSMachineClass ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:28.187921   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.PersistentVolumeClaim ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:28.187939   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.Node ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
•W0908 17:43:28.291174   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.AWSMachineClass ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:28.291197   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.PersistentVolumeClaim ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:28.291208   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.MachineSet ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:28.291216   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.Node ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:28.291215   25211 reflector.go:301] k8s.io/client-go/informers/factory.go:134: watch of *v1.PersistentVolume ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:28.291226   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.MachineDeployment ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
W0908 17:43:28.291231   25211 reflector.go:301] pkg/client/informers/externalversions/factory.go:117: watch of *v1alpha1.GCPMachineClass ended with: very short watch: pkg/client/informers/externalversions/factory.go:117: Unexpected watch close - watch lasted less than a second and no items received
•W0908 17:43:28.393691   25211 
```

I am re runninng the tests to double-check the same.

**Comment by majst01** [comment]
Thanks will have a look

**Comment by majst01** [comment]
It comes down to one test failure (down from 3 after updating ginko/gomega as well):

```
• Failure [0.111 seconds]
#machine_safety ##reconcileClusterMachineSafetyOvershooting [It] Unfreeze machineDeployment manually and also triggers machineSet to be unfrozen 
/home/stefan/dev/github.com/gardener/machine-controller-manager/pkg/controller/machine_safety_test.go:484

  Expected
      <map[string]string | len:2>: {"freeze": "True", "machine": "test"}
  to equal
      <map[string]string | len:1>: {"machine": "test"}

```

I am not really familiar with ginko/gomega and your tests, does anything comes up in your mind which might cause this ?

**Comment by hardikdr** [comment]
>does anything comes up in your mind which might cause this ?

Hm, the safety controller's test should ideally fail due to a dependency upgrade. I'll take a look tomorrow.

**Comment by majst01** [comment]
Thanks

**Comment by hardikdr** [comment]
I ran the unit tests locally, I see many warnings:
```
W0911 09:29:22.516204   77013 reflector.go:301] pkg/mod/k8s.io/client-go@v0.16.15/tools/cache/reflector.go:96: watch of *v1alpha1.GCPMachineClass ended with: very short watch: pkg/mod/k8s.io/client-go@v0.16.15/tools/cache/reflector.go:96: Unexpected watch close - watch lasted less than a second and no items received
W0911 09:29:22.516219   77013 reflector.go:301] pkg/mod/k8s.io/client-go@v0.16.15/tools/cache/reflector.go:96: watch of *v1.Secret ended with: very short watch: pkg/mod/k8s.io/client-go@v0.16.15/tools/cache/reflector.go:96: Unexpected watch close - watch lasted less than a second and no items received
W0911 09:29:22.516260   77013 reflector.go:301] pkg/mod/k8s.io/client-go@v0.16.15/tools/cache/reflector.go:96: watch of *v1.Node ended with: very short watch: pkg/mod/k8s.io/client-go@v0.16.15/tools/cache/reflector.go:96: Unexpected watch close - watch lasted less than a second and no items received
```

I also see the tests are actually flaky. Multiple runs of unit tests gave diff number of failures.
Seems, certain default timeout in the upstream client-go has changed, bringing flakiness.

Btw, I am planning to bump the version of k8s.io dependency anyways to `0.18.0` in near future, I'd need it for the autoscaler rebase.
- it has breaking changes in the client-call definitions, so would require more refactoring in the code.

Unfortunately, I don't have the immediate capacity to look further deeper into it, maybe either you can find it what's actually happening underneath causing unit tests to flake, or I can check later next week. :)

**Comment by hardikdr** [comment]
I couldn't take this up yet, hope it's not a pressing need for you @majst01, I can otherwise suggest you try re-vendoring MCM to k8s 1.18. I know there are breaking changes in terms of client-call, that'd have to be adapted in the code.

**Comment by majst01** [comment]
Im closing this.

**Pull request closed without merging**
