### PR TITLE
Use channel id for posting slack release notes

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
Use the channel id for posting slack release notes so that the definition does not need to be adapted in case the channel will be renamed

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by ggaurav10** [comment]
/hold
might need to change the workspace too

**Comment by prashanth26** [comment]
@ggaurav10 - Good catch.
@petersutter -  Do we have to update the workspace?

**Comment by petersutter** [comment]
see reply here https://github.com/gardener/etcd-backup-restore/pull/248#issuecomment-659605630
it's not a must. Both work as they have the same api_token

**Comment by ggaurav10** [comment]
Thanks Peter for the clarification
/unhold
/lgtm
/approve

**Comment by hardikdr** [comment]
I'll go ahead merging this, seems the tests are failing due to unrelated reasons or is it otherwise?

**Comment by prashanth26** [comment]
tests are passing now. Merging.

**Pull request merged**
