### PR TITLE
Updated content structure

### PR DESCRIPTION
**Pull request by n-boshnakov**
**What this PR does / why we need it**:
This PR updates the content structure of the mcm content and fixes the titles of certain topics.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

### CODE REVIEW

**Comment by JordanJordanov** [comment]
@n-boshnakov - let's add also the personas, e.g.
- deployment -> developer + operator
- development -> developer
- docs (we shall probably rename that folder) -> developer
- proposals -> developer
- usage -> user+operator

**Comment by n-boshnakov** [comment]
> @n-boshnakov - let's add also the personas, e.g.
> 
> * deployment -> developer + operator
> * development -> developer
> * docs (we shall probably rename that folder) -> developer
> * proposals -> developer
> * usage -> user+operator

The personas have been added and the folder name has been changed, with the new name reflected in the .yaml file.

**Review by JordanJordanov — APPROVED** [review]
/lgtm

**Review by himanshu-kun — APPROVED** [review]
/lgtm

**Pull request merged**
