### PR TITLE
OpenStack: Print API request/response debug, when verbosity is set to 6

### PR DESCRIPTION
**Pull request by kayrus**
**What this PR does / why we need it**:

Setting the verbosity to 6 allows to print detailed OpenStack API requests/responses.

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Openstack: Print API request/response debug when verbosity is set to 6
```

cc @rfranzke . It might be an idea to introduce an interface to enable verbose logging dynamically, because if you change the manifest for one particular shoot, it will be reconciled with the defaults. Any thoughts on how to do this?

### CODE REVIEW

**Comment by kayrus** [comment]
@mvladev Is it possible to use `/configz` http handler to dynamically modify the klog verbosity settings?

**Comment by prashanth26** [comment]
> It might be an idea to introduce an interface to enable verbose logging dynamically, because if you change the manifest for one particular shoot, it will be reconciled with the defaults. Any thoughts on how to do this?

Last I checked this is not possible. Refer - https://github.com/google/glog/issues/452.

**Comment by kayrus** [comment]
@prashanth26 fine. BTW: glog is not used here, but klog.

**Comment by hardikdr** [comment]
I would be really interested in knowing if there is a good way to dynamically update the log levels. Do you have suggestions, around how can that be achieved with klog ?

**Comment by kayrus** [comment]
> As we don't have CI configured for OpenStack, I am curious if you got a chance to test this PR, if works as expected ?

@dkistner @dguendisch @rfranzke can you test this change against openstack environment?

> I would be really interested in knowing if there is a good way to dynamically update the log levels. Do you have suggestions, around how can that be achieved with klog ?

I don't think this is impossible and I already have an idea, but I'd focus on dynamic logic within a separate PR

**Comment by hardikdr** [comment]
>I don't think this is impossible and I already have an idea, but I'd focus on dynamic logic within a separate PR

Sure, thanks. 
I'll then go ahead and merge this one soon, later I will try to find some time to test the openstack provider separately before next mcm release.

**Pull request merged**
